### ISSUE TITLE
Correct roi setting debug trace ?

### ISSUE THREAD

**Issue by marila31** [chyan26/RaptorServ#1]
The command roi 1 1 32 32 is accepted and functional.
It selects a roi of 32 x 32 pixels.
But the associated debug trace is:
image ROI setting is: x0=1 x1=1 y0=32 y1=32
...meaning a roi of 1 x 1 pixel ?
I think that the debug trace should be corrected.

**Comment by chyan26** [comment]
If the ROI is 32x32, there is typo in the code.  See here

3081       cfht_logv(CFHT_MAIN, CFHT_DEBUG,
            "(%s:%d) image ROI setting is: x0=%i x1=%i y0=%i y1=%i",
           **FILE**, **LINE**, x0, y0, x1, y1);

They should be 

3081       cfht_logv(CFHT_MAIN, CFHT_DEBUG,
            "(%s:%d) image ROI setting is: x0=%i y0=%i x1=%i y1=%i",
           **FILE**, **LINE**, x0, y0, x1, y1);

**Comment by marila31** [comment]
The argument check needs to be changed to:
           if (cargc != 4 ){
                   sprintf(buffer, "%c %s \"Input FOUR numbers to set ROI.\"",
Because with 5 there is an error:
Sep 21  1:33:21.68 root   debug - RaptorServ(4611): (raptorServ.c:2540) RECV> roi 1 1 32 32.
Sep 21  1:33:21.68 root   debug - RaptorServ(4611): (raptorServ.c:3030) SEND> ! ROI "Input FOUR numbers to set ROI.".

**Comment by chyan26** [comment]
1.  Selecting the ROI.
Four number is required to input (x0,y0) (x1,y1).  According to my note, x0,y0 should be the lower-left corner and x1,y1 is the upper-right corner.  This should be consistent with the suggested convention.

2. centroid calculation in calculateCentroidMPFIT
In this function, the result of the centroid calculation will be returned in xc and yc.  If my understanding is correct, to transform them into bottom-left convention is just to change the serv_info->guide_yoff.

  serv_info->guide_yoff=GUIDE_SIZE_Y-yc;

This is because the conversion between two system is only happened in Y-direction.  The X is remain the same.
